### ISSUE TITLE
Péhápkaři - "Corporate" Identity

### ISSUE THREAD

**Issue by jakubkratina** [pehapkari/Community#10]
## Keywords
- **vzdělávání**
- **srazy**
- přednášky
- livestreamy
- školení
- články
- slack

**Comment by chemix** [comment]
bude se resit 9.6

**Comment by jakubkratina** [comment]
Aktuální big task je definovat CI PéHáPkařů, společně s tvorbou nového webu, materiály a podklady pro videa.

# CI

- logo je a zůstane aktuální
- barvy se budou řešit a nějaké inspirace jsou v #6 
- určitě by se hodily vizitky pro firmy a domluvání srazů atp.

# Web

- máme hodně aktivit (viz toto issue nahoře) + další zdroje a kanály viz slack, youtube, atp.
- tyto aktivity je jednoznačně potřeba lépe komunikovat,
- nový člověk, který se doslechne o nás a přijde na náš web, by měl vědět, co jsme mu schopni nabídnout, ať už srazy, streamy, slack, mentoring, školení, články atp.
- každá z hlavních sekcí (srazy, streamy, školení,..) bude mít vlastní stránku, na které budou všechny informace (např. v sekci YouTube bude seznam videí, natažených pomocí YouTube API a možnost si to rovnou přehrát)
- přehledné odkazy na všechny možné eventy (streamy, srazy, ..)

# Materiály

- vizitky pro obchodní aktivity (domlouvání srazů atp.)

# Podklady pro videa

- kvalitní intro a outro 

# Leták 

- již hotový, pro vysoké školy a akvizici nových členů komunity

# Komunikace

- #5, #12, #6 , #9

**Comment by landsman** [comment]
Btw co založit nějaké občanské sdružení, či něco podobného, aby to byla víc oficiální organizace? Mohlo by se to v budoucnu hodit. Čeští drupalisté něco takového mají myslím, viď @radimklaska?

**Comment by TomasVotruba** [comment]
@landsman Tohle řešíme na pátečních osobních meetupech, protože na Github se to neukázalo jako efektivní. Můžeš se přidat, jen přes prázdniny je to volnější :sun_with_face:  :beer:

**Comment by JanSuchanek** [comment]
@TomasVotruba Pokud by jste někdy řešili občanský sdružení nebo zapsaný spolek, tak určitě o výhodách a nevýhodách poradí kluci z jmnet.cz

**Comment by radimklaska** [comment]
Ano, Asociace pro Drupal je zapsany spolek. Umoznilo nam to hlavne primo komunikovat se sponzory - to byl driv velky problem.

**Comment by TomasVotruba** [comment]
Outdated, new web in progress
