### ISSUE TITLE
[core meetup] pátek 9. 6.

### ISSUE THREAD

**Issue by TomasVotruba** [pehapkari/Community#12]
**Kde?** [Zetko](http://www.zetkovkotve.cz/), Kotva, Praha
**Kdy?** 12-14 hod.

Nejblíž je zastávka metra Nám. Republiky na žluté (nebo i šalina)

## Téma - Jak vypadáme - design webu, UX a identita

- #10 

## Bude followup

- #5

**Comment by TomasVotruba** [comment]
@jkuchar Honzo, mohl bys nám prosím sepsat stručné závěry či návrhy z tvého výzkumu UX?
Ať to můžeme použít dál a je to v pohybu a neumře to v písku času.

**Comment by TomasVotruba** [comment]
Už bylo, zavírám

**Comment by TomasVotruba** [comment]
@jkuchar Máš chuť se v tom aktivně angažovat?

**Comment by jkuchar** [comment]
Ano, jen jsem teď pořád někde na cestách. Za měsíc tedy nejdříve mohu začít něco dělat. 

27. 7. 2017 v 22:09, Tomáš Votruba <notifications@github.com>:

**Comment by TomasVotruba** [comment]
Už se to táhne měsíc a půl a web potřebujeme řešit dříve a flexibilněji. Díky za odpověď.

**Comment by jakubkratina** [comment]
@TomasVotruba vezmem na to Leu?

**Comment by jakubkratina** [comment]
@TomasVotruba vezmem na to Leu?

**Comment by TomasVotruba** [comment]
To bych nechal na osobní meetup
