### ISSUE TITLE
[core meetup] pátek 16. 6. 

### ISSUE THREAD

**Issue by chemix** [pehapkari/Community#13]
Přijít může každý, kdo chce dlouhodobě aktivně podílet (pár hodin týdně) na budování Péhápkařů a mít to časem jako placenou práci. která ho bude naplňovat.

## Kdy

- ~ 13:30—15 hod.

## Kde

- [Zetko](http://www.zetkovkotve.cz/)
- nebo FB live, už jsme takhle byli 2x a šlo to :)

## Todo

- [] poslat pozvánku na Google Calendar

## Co probrat

- Corporate Identity
- Prazdninove akce
- Podstata webu (persony?, obsah? cílení?)

cokoli dalsiho?

**Comment by jakubkratina** [comment]
@chemix proč ne Żetko?

**Comment by TomasVotruba** [comment]
Zetko je ok!

**Comment by chemix** [comment]
kopiroval jsem to z minule akce tak jsem to nechal ... ale tak jsem to tedy nahradil za zetko ;-)

**Comment by chemix** [comment]
Akce probehla, moc se nam libila. Resili se hlavne prazdninove akce. 

- PHP Beer Trip 
- Pehapkari meetups
- Nette Camp - otevreny pro vsechny PHP vyvojare, temata PHP, Docker, Testovani, ORM
- ?? Nette Voda ?? 
- ?? Summer Of PHP Code ??
