### ISSUE TITLE
[core meetup] pátek 30. 6.

### ISSUE THREAD

**Issue by chemix** [pehapkari/Community#14]
**Kde?** [Zetko](http://www.zetkovkotve.cz), Kotva, Praha
**Kdy?** 11-13 hod.

Nejblíž je zastávka metra Nám. Republiky na žluté (nebo i šalina)

**Comment by TomasVotruba** [comment]
Děkuju za vytvoření, Honzo

**Comment by chemix** [comment]
spis co se bude resit? mame tam neco aktualniho? s cim se da pohnout?

**Comment by TomasVotruba** [comment]
Co máme teď otevřené a potřebujem posunout:

- web a co na něm má být
- leták a jeho tisk

**Comment by jakubkratina** [comment]
Na mně je pak ještě ta nabídka do firem a zajímá mě, jak to je s dalším srazem a jak dopadlo pivo :)

**Comment by jakubkratina** [comment]
- livestream anketa

**Comment by jakubkratina** [comment]
- [ ] domluvit lidi na livestreamy (Jakub rozhodí sítě na Tomáše a Honzu)
- [x] pingnout Leu s úpravou letáku (Jakub)
- [x] potlačit Honzu Kuchaře viz https://github.com/pehapkari/Community/issues/12 (Tomáš)
- [ ] dotlačit PéHáPkaři nabídku (Jakub)
- [x] vytvořit sdílený google kalendář (kam házet události)

**Comment by jakubkratina** [comment]
![bw v2](https://user-images.githubusercontent.com/712021/27788944-cadf6526-5fea-11e7-9d9e-6ef58b9a2401.jpg)

---

![bw](https://user-images.githubusercontent.com/712021/27788945-cadfdec0-5fea-11e7-9e72-f9175416bb1c.jpg)

---

![colorrrr](https://user-images.githubusercontent.com/712021/27788946-cae5995a-5fea-11e7-8c67-316f17c95e6e.jpg)

Lea se ptá jakou verzi chceme připravit na tisk. @chemix @TomasVotruba

**Comment by TomasVotruba** [comment]
Mně se líbí nejvíc 2.

**Comment by chemix** [comment]
Me napad co tu dvojku zkusit doplnit o emoji? pivo, hodiny, speakra :-)

jinak jsem take pro 2.

**Comment by jakubkratina** [comment]
![bw emoji 2](https://user-images.githubusercontent.com/712021/27834750-6f9ee0ee-60d8-11e7-8c09-51d78a33ff91.jpg)
 
Lea: "inak emoji je dobry napad, resp. ja to rada pozuivam 😀 otazka je, aky efekt to bude mat na cielovku, ale tou ste vlastne vy, takze ak vy ste za, tak ja som tiez!
"

@chemix @TomasVotruba ?

**Comment by TomasVotruba** [comment]
Jsem tak 50/50. Jak ten text široký, tak se mi to tam nehodí. Spíš bych to použil místo slov než za ně: "jdeme na :beer: "

After all, můžem udělat 2 plakáty :+1:

**Comment by leapetrasova** [comment]
@TomasVotruba mna ta sirka textu moc neuraza, resp. som na to celkom zvyknuta z instagramu a pod. co keby ste tie varianty skusili ukazat este par ludom? s otazkou, ze ktore plagat toho cloveka viac zaujal/prisiel sympatickejsi?

**Comment by leapetrasova** [comment]
@TomasVotruba pouzitie namiesto slov mi trosku pirlis pripomina prvy rocnik zakladnej skoly :/

**Comment by TomasVotruba** [comment]
Good idea. Hodíš to na fb Kubo?

**Comment by TomasVotruba** [comment]
Si zabila! Tak to mám s tou duplikaci :)

**Comment by jakubkratina** [comment]
Proč si připadám jak pošťák? :D jojo

**Comment by TomasVotruba** [comment]
Netahej sem tarateku! :Pro
Díky 😘 kiss

**Comment by mabar** [comment]
Bez emoji. Čisté a spartánské, přesně tak vidím práci backendisty :D

Edit. Ten úplně čistý, bez <?php. Případně ten s gradientem.

**Comment by jakubkratina** [comment]
Tak to vypadá, že lid promluvil (viz fb). Půjdeme do varianty bez emojis, tzn. dvojka. Souhlasíte?

**Comment by TomasVotruba** [comment]
@jakubkratina Díky bratře. Ano!

**Comment by chemix** [comment]
ja chci jeden barevnej s emoji :-) (prosiiiim)

**Comment by leapetrasova** [comment]
mozete mi prosim vygenerovat QRko, ktore bude viest na pehapkari.cz, ale cez nejaky analytics link, aby sme vedeli spocitat, kolko ludi slo cez QR? 

to je to posledne co chyba :) idealne v nejakom vektorovom formate

**Comment by jakubkratina** [comment]
@leapetrasova [pehapkari-qr.svg.zip](https://github.com/pehapkari/Community/files/1129306/pehapkari-qr.svg.zip)

**Comment by leapetrasova** [comment]
![image](https://user-images.githubusercontent.com/7047013/27958942-9fe43ad4-6325-11e7-9958-078b854ef3f4.png)

tak to skuste. pre istotu printnite jeden, pozrite na to  a nahlaste pripadne nedostatky :D

**Comment by leapetrasova** [comment]
pozeram za na webe sa to rendruje skarede ako noc, ale pre print by malo byt vsetko OK. snad. 😁

**Comment by leapetrasova** [comment]
aha vidim preco, pretoze sa to znejakeho dovodu premrda na PNG? weird, ja to radsej nazdielam 
https://www.dropbox.com/s/exmh3ys9o7skmk6/pehapkari-print2.pdf?dl=0

**Comment by jakubkratina** [comment]
@leapetrasova omlouvám se, doplnil jsem ještě URL o jeden UTM parametr, posílám nový QR kód, uprav to prosím :/
[pehapkari-qr.svg.zip](https://github.com/pehapkari/Community/files/1131080/pehapkari-qr.svg.zip)

**Comment by leapetrasova** [comment]
https://www.dropbox.com/s/c75lfqlepta0wt9/pehapkari_print3.pdf?dl=0

**Comment by TomasVotruba** [comment]
Meetup hotov
