### ISSUE TITLE
Kam zanést letáky?

### ISSUE THREAD

**Issue by TomasVotruba** [pehapkari/Community#16]
Leták už máme hotový a vytisknutý: #6   :+1: 

V Praze školy tolik neznám, tak se ptám, kam je hodit? 
S odkazem na mapku prosím.

---

### Praha

- UK, Matematicko fyzikální fakulta na Karláku - [mapka](https://www.google.cz/maps/place/Univerzita+Karlova,+Matematicko-fyzik%C3%A1ln%C3%AD+fakulta/@50.069968,14.4277818,19.14z/data=!4m13!1m7!3m6!1s0x470b94f47896c3ab:0x6f9ed77ae3f8584d!2zS2FybG92byBuw6FtLiwgTm92w6kgTcSbc3RvLCBQcmFoYQ!3b1!8m2!3d50.0757387!4d14.4200559!3m4!1s0x470b948a06d3f999:0x63925329af44b125!8m2!3d50.0701023!4d14.428124)

### Brno

- ...

**Comment by chemix** [comment]
Národní technická knihovna - [mapa](https://www.google.cz/maps/place/N%C3%A1rodn%C3%AD+technick%C3%A1+knihovna/@50.1039236,14.3907032,15z/data=!4m2!3m1!1s0x0:0x917af83b84a0902?sa=X&ved=0ahUKEwiFj72TwZjXAhVhDsAKHSE0DVwQ_BIIgwEwEQ)

**Comment by tomtomklima** [comment]
Umím NTK + ČVUT + MatFyz na Křižíkově

**Comment by grogy** [comment]
FIT ČVUT, 2. patro hned u studijního oddělení. - http://www.openstreetmap.org/?mlat=50.104769468307495&mlon=14.389686584472656#map=16/50.1048/14.3897

**Comment by tomasfejfar** [comment]
@pehapkari/core mohli byste mě někdo odebrat z assignees? Straší mi to v reportu a nemůžu se odebrat sám :(

Update: Tak už jo. Byl to asi nějaký glitch.

**Comment by TomasVotruba** [comment]
@tomasfejfar Co je report? Máš link?

**Comment by enumag** [comment]
@TomasVotruba Patrně myslí https://github.com/issues/assigned.

**Comment by tomasfejfar** [comment]
Jo, sorry ;)

**Comment by TomasVotruba** [comment]
Outdated
