### ISSUE TITLE
[meetup] Planette sraz Prague

### ISSUE THREAD

**Issue by TomasVotruba** [pehapkari/Community#4]
> @f3l1x V nedeli se vratim ze Spanelska. Co se sejit v Praze a prodiskutovat to nekdy v dalsim tydnu?

22-26. května

**Comment by TomasVotruba** [comment]
Já můžu kdykoliv krom po dopoledne a pátek odpoledne.

**Comment by TomasVotruba** [comment]
@f3l1x Jak to vidíš? Nějaký updates?

**Comment by chemix** [comment]
resil bych to pres slack at nam to tu nestrasi :)

**Comment by f3l1x** [comment]
Planette sraz teda 12.6.2017 ;-) Ciste nahodou. 

@TomasVotruba @dg @chemix @paveljanda

**Comment by TomasVotruba** [comment]
Budeme tam :), pozval jsem i @paveljanda

[Kavárna Jedna](http://cafejedna.cz/), 16-19 hod.

Nejblíž je červené metro Vltavská, ještě blíž zastávka tramvaje Veletržní palác

**Comment by TomasVotruba** [comment]
Díky Honzo!
