### ISSUE TITLE
Jednoduchá UX analýza webu Péhápkaři.cz

### ISSUE THREAD

**Issue by TomasVotruba** [pehapkari/Community#5]
Bavil jsem se @jkuchar, jestli by nemrknul na web a nesepsal pár připomínek, co by šlo zlepšit z UX hlediska.
Já mám autorskou slepotu a web používám denně, takže vím prd, jak se používá novým lidem.

*Note: toto je můj draft z hlavy na základě volného psaní.*

Na požádání Honzy tady píšu odpovědi na 2 otázky:

### Jaké jsou cíle Péhápkařů

- **zlepšovat úroveň znalostí v PHP** - přednášky, livestreamy, školení, články
- **vytvářet bezpečné prostředí pro seberealizaci v rámci komunity** - chceš dělat livestreamy nebo srazy? pomůže ti to nakopnout; nebo umíš s UX? realizuje se na našem amatérském webu

### Jaké jsou cíle webu Pehapkari.cz

- abych se dověděl, že vůbec existuje nějaká PHP komunita, **co od ní můžu získat jako PHP programátor**
- abych jako nováček rychle našel místo, kde **se můžu zeptat nebo něco naučit** - Slack, FB stránka, Livesteramy a Youtube videa
- abych zjistil, kam a kdy můžu **přijít osobně na sraz** - Facebook stránka, Eventigo

Takhle nějak Honzo? Klidně se doptávej a směruj mě.

**Comment by TomasVotruba** [comment]
@jkuchar  Honzo, po 10 dnech bych potřeboval nějaké info. Jak to vidíš? Můžeme si stanovit nějaký termín, ať se to hýbe a vím s čím a kdy počítat? Potřeboval bych to, abychom mohli plánovat jiné aktivity, spolupracujeme s grafikem atp.

+ Využili bychom to i v jiných úkolech: #6, #9, #10

Jestli tu jsou nějaké blockery, dej vědět, můžeme ti s nima pomoc.

**Comment by jkuchar** [comment]
Děkuji za soupis, Zkusím k tomu vymyslet otázky...

> jestli by nemrknul na web a nesepsal pár připomínek, co by šlo zlepšit z UX hlediska.
Já mám autorskou slepotu a web používám denně, takže vím prd, jak se používá novým lidem.

Máš nějaké věci, které bys rád ověřil? Jaké jsou tvé očekávání? Co bys rád zjistil? Na soupis cílů webu a pehapkařů jsem se ptal, protože jsem chtěl vyzkoušel i jestli je message pehapkařů jasná.

Mohu zkusit poté zkombinovat i s výzkumem použitelností a zjistit, jak se lidé na webu orientují... Napadají tě nějaké tasky, které by ma weby měly umět vykonat (a proč)?

Tento týden bych se k tomuto měl konečně dostat a podniknout první kroky. Do kdy bys potřeboval mít výstup?

**Comment by TomasVotruba** [comment]
Tak mě napadá, že tohle téma - design, UX, corporate identity - budeme řešit tento pátek na setkání v Praze (s @jakubkratina a @chemix ), tak by bylo fajn to spojit. Moc rád bych tě tam měl.

Kdy přesně? **9. 6.** 12-14 hod.

Můžeš se zapojit i hangoutem, běžně tam jeden z nás je takhle "mimo" :)

Co ty na to?

**Comment by jkuchar** [comment]
Koupil jsem jízdenky, dojedu tedy.

**Comment by TomasVotruba** [comment]
Fajné, seš borec :+1:

**Comment by TomasVotruba** [comment]
Probrali jsme osobně na meetupu s aktuálními informacemi. Uzavírám a bude nové issue :)
