### ISSUE TITLE
Leták

### ISSUE THREAD

**Issue by jakubkratina** [pehapkari/Community#6]
Na meetingu jsme navrhli, že by stálo za to oslovit lidi offline, pomocí letáku.

# Otázky
1. Co je cílem letáku?
2. Koho chceme oslovit?
3. Jak ho oslovíme (kam letáky rozneseme)?
4. Měl by se design něčeho držet?
5. Je nějaký maximální budget pro tvorbu letáku?
6. Protože ještě nemáme společnou kasičku (ikdyž, máme transparentní účet), jak budou letáky financovány?

Cíle Péhápkařů: https://github.com/pehapkari/Community/issues/5

**Comment by TomasVotruba** [comment]
Díky za vytvoření samostatnýho issue, to půjde líp.

## Odpovědi

1. říct funkce komunity v #5 - "Jaké jsou cíle webu Pehapkari.cz" (případně viz https://github.com/pehapkari/Community/issues/10)
2. primárně studenty VŠ, sekundárně lidi cowork centrech
3. výšky, coworking centra + IT akce, srazy
4. asi jen loga https://pehapkari.cz/, to je ke stažení tady: https://pehapkari.cz/press/, jinak se meze nekladou 
   - Naše CI je definováno webem, tzn. barvy, font, atp. dle https://pehapkari.cz/
5. nejlíp do 1 000 Kč
6. zatím z našich dotací [z otevřeného účtu](https://www.fio.cz/ib2/transparent?a=2301196632)

**Comment by jakubkratina** [comment]
Zkus mi odpovědět prosím na co nejvíc otázka, pak to posunu dál. Každý názor se cení :)

**Comment by TomasVotruba** [comment]
@jakubkratina Odpověděl jsem na všechno, ale mezitím přibyly otázky :-D
Můžeš to prosím očíslovat? Ať se neztratíme.

+ Nerozumím asi té větě, jestli chceš odpovědi po mně nebo po ostatních.

**Comment by jakubkratina** [comment]
@TomasVotruba Jak jsi psal, mezitím přibyly otázky :) Takhle super. Má k tomu @chemix něco?

**Comment by chemix** [comment]
nemam :)

**Comment by jakubkratina** [comment]
Naše CI je definováno webem, tzn. barvy, font, atp. dle https://pehapkari.cz/

**Comment by jakubkratina** [comment]
Otázky od Lei: https://docs.google.com/document/d/1aPDmtIfyj78TjBFAT0fNpomTYmsL0Fo-9BzzSTe6i8Y/edit

**Comment by TomasVotruba** [comment]
![bw](https://user-images.githubusercontent.com/924196/27226851-2d96f4f6-52a1-11e7-9b59-162ccbac691c.png)
![colorrrr](https://user-images.githubusercontent.com/924196/27226852-2dab414a-52a1-11e7-9e38-553f22d88d85.png)

**Comment by jakubkratina** [comment]
Tu poslední větu o zajímavý práci bych nahradil něčím o vzdělávání - o tom tam nic není.

**Comment by TomasVotruba** [comment]
- "promluví 2 speakři"

- "v 18 hodin" na stejném řádku

**Comment by tomasfejfar** [comment]
Myslím, že se pouze zajímavá a ne zaujímava, ne? (Poslední věta)

**Comment by jakubkratina** [comment]
@tomasfejfar Určitě, Lea, která to psala, je z východní Evropy, tak to tam nechala :D

**Comment by TomasVotruba** [comment]
PDF here, ať se neztratí: https://www.dropbox.com/s/c75lfqlepta0wt9/pehapkari_print3.pdf?dl=0

- [ ] dát do tisku, až budou hotové nálepky (@TomasVotruba)

**Comment by TomasVotruba** [comment]
Napsáno Dendovi!

**Comment by leapetrasova** [comment]
[pehapkari_print_BW.pdf](https://github.com/pehapkari/Community/files/1318156/pehapkari_print_BW.pdf)
[pehapkari_print_COLOR.pdf](https://github.com/pehapkari/Community/files/1318157/pehapkari_print_COLOR.pdf)
