### ISSUE TITLE
Livestream - Rozhovory

### ISSUE THREAD

**Issue by jakubkratina** [pehapkari/Community#7]
Nedávno jsme se na večeři s Martinem Froňkem dobrali tomu, že Martinův stream, který má 13. června, bude nejlepší formou rozhovoru.

To mě navedlo na myšlenku zavést nepravidelné livestreamy na téma "Rozhovory s vývojáři", případně s IT lidma. 

Představte si to jako DVTV nebo Standa show, akorát více technicky zaměřené.

Ikdyž by mě to bavilo, ne že ne, tak mi do role moderátora úplně pasuje @TomasVotruba, protože se umí skvěle ptát.

Co si o tom myslíte? Kdo vás napadne, že bychom s ním mohli udělat rozhovor?

**Comment by jakubkratina** [comment]
- David Grudl (o Nette a jeho aktuální averzi k vývoji)
- Patrik Votoček (Shipito, https://getfullstackteam.com/, aktuální job (GoDaddy?)) 
- Filip Procházka (Kdyby, open source)

**Comment by TomasVotruba** [comment]
@todo Připsat vlastní nápady

**Comment by TomasVotruba** [comment]
Tohle už je asi vyřízené, když ti to krásně jede.

Můžem zavřít?

**Comment by jakubkratina** [comment]
Klidně jo, mám to v hlavě
