### ISSUE TITLE
Livestream/YT intro & outro & midtro & overlay

### ISSUE THREAD

**Issue by jakubkratina** [pehapkari/Community#9]
Rád bych povýšil livestream o nějakou grafiku.

## Intro
Pár vteřinové intro, které bude před každým streamem, stejně tak ideálně před každým videem na YT.

Nejspíš by tam měly zaznít klíčová slova viz https://github.com/pehapkari/Community/issues/10 a logo. Možná i odkaz na web (jakože ikonka že web, slack, fb a tw), to ale možná do outra.

Dokážu si to představu třeba jako zde: https://www.youtube.com/watch?v=VNgc6YAJ8Uo (8. vteřina) nebo https://www.youtube.com/watch?v=GxHx30c9-iw.

## Outro
Tady jde o ty odkazy, tzn. logo + kam dál, tzn. fb, slack, web, twitter, trvání třeba 10s.

2 videa - levá část na nějaké předchozí, pravá část povede na subscribe

Např. https://youtu.be/GxHx30c9-iw?t=24m3s

## Midtro
Tzv. znělka. Tzn. pokud třeba dělám livestream a dokončím téma, nahodí se tahle cca 2s znělka a plynule se přejde do dalšího tématu. Dokážu si to představit jen jako logo na bílým pozadí, s nějakou grafikou, přechodem.

## Overlay
Chtěl bych přidat trochu grafiky do livestreamů. Nyní to je tak, že v levém dolním rohu je logo a v pravém webka.

Potřeboval bych přidat spodní lištu, na které bychom mohli v průběhu livestreamu komunikovat zprávy, např.

- Livestream každé 2. úterý od 19:00, více na facebook.com/pehapkari
- Další sraz 30. května, více na,...
- Staň se členem, běž na ....

Toto overlay se bude zobrazovat jednou za čas nebo sporadicky, tzn. musí umět fungovat s logem, které může být pořád vlevo dole.

Pak si dokážu představit, když se přidá nový follower, tak z levé horní části vyjede nějaká grafika, kde bude "Nový follower **Pepa**" + bych tam přidal tu animaci slona (přidám).

![eleph](https://cloud.githubusercontent.com/assets/712021/26399018/b4a5e2fa-407b-11e7-8597-a80ace961bc9.gif)

+ u intra&outra&midtra nějaký zvuk/hudba

@chemix říkal, že by, pokud to bylo jednoduchý, mohl zvládnout. Nemáme žádný PéHápkařský CI, tak bychom ho tímhle mohli zkusit vykopnout.

[Big picture](https://github.com/pehapkari/Community/issues/5)

**Comment by chemix** [comment]
takovehle lehci veci bych zvladnul. Toho gifoveho slona bych nahradil nejakou variaci loga ... jen teda v patek sepisem scenare a texty pro jednotlive klipy a ja je pak pripravim.

**Comment by jakubkratina** [comment]
Pecka! Zvládneš i vytvořit z toho slona nějakou animaci?

**Comment by chemix** [comment]
zas bych to pro prvni iteraci neprehanel :)

**Comment by jakubkratina** [comment]
Ale no tak, kazíš mi radost :( :D

**Comment by chemix** [comment]
animovani je na dlouho ... jedem mvp :)

**Comment by jakubkratina** [comment]
Jasan

**Comment by chemix** [comment]
zdroje v repu

**Comment by TomasVotruba** [comment]
Hotovo, zavírám
